FIND_PATH(LOG4CXX_INCLUDE_DIR logger.h 
          PATHS ${TARGET_BUILD_DIRECTORY}/include/log4cxx 
)
#find_library(LOG4CXXD_LIBRARY NAMES log4cxx${CMAKE_DEBUG_POSTFIX} ${LOG4CXX_LIBRARY_HINTS})
FIND_LIBRARY(LOG4CXX_LIBRARIES 
            NAMES log4cxx
            PATHS ${TARGET_BUILD_DIRECTORY}/lib
)

#message (STATUS "LOG4CXX_INCLUDE_DIR : ${LOG4CXX_INCLUDE_DIR} LOG4CXX_LIBRARIES : ${LOG4CXX_LIBRARIES}")

MARK_AS_ADVANCED(LOG4CXX_INCLUDE_DIR LOG4CXX_LIBRARIES) 
