if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    message(STATUS "Setting build type to 'Debug' as none was specified.")
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Choose the type of build." FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
endif()

if(BUILD_SHARED_LIBS)
        set(CMAKE_DEBUG_POSTFIX 			"${STATIC_POSTFIX}.d" 	CACHE STRING "Set Debug library postfix" FORCE)
        set(CMAKE_RELEASE_POSTFIX 			"${STATIC_POSTFIX}" 	CACHE STRING "Set Release library postfix" FORCE)
        set(CMAKE_MINSIZEREL_POSTFIX 		"${STATIC_POSTFIX}" 	CACHE STRING "Set MinSizeRel library postfix" FORCE)
        set(CMAKE_RELWITHDEBINFO_POSTFIX 	"${STATIC_POSTFIX}" 	CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
        set(CMAKE_FIND_LIBRARY_SUFFIXES 	"${STATIC_POSTFIX}.so" 	CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
        set(CMAKE_FIND_LIBRARY_PREFIXES 	"${STATIC_POSTFIX}lib" 	CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
else(BUILD_SHARED_LIBS)
        set(CMAKE_DEBUG_POSTFIX 			".d" 	CACHE STRING "Set Debug library postfix" FORCE)
        set(CMAKE_RELEASE_POSTFIX 			"" 		CACHE STRING "Set Release library postfix" FORCE)
        set(CMAKE_MINSIZEREL_POSTFIX 		"" 		CACHE STRING "Set MinSizeRel library postfix" FORCE)
        set(CMAKE_RELWITHDEBINFO_POSTFIX 	"" 		CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
        set(CMAKE_FIND_LIBRARY_SUFFIXES 	".a"  	CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
        set(CMAKE_FIND_LIBRARY_PREFIXES 	"lib"  	CACHE STRING "Set RelWithDebInfo library postfix" FORCE)
endif(BUILD_SHARED_LIBS)

if(UNIX)
    set(CMAKE_CXX_OUTPUT_EXTENSION .o)
else(UNIX)
    set(CMAKE_CXX_OUTPUT_EXTENSION .o)
endif(UNIX)

#if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
#    set(CMAKE_DEBUG_POSTFIX "d")
#    set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
#    set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
#elseif("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
#    set(CMAKE_FIND_LIBRARY_SUFFIXES ".so")
#    set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
#else()
